read nfc tag
himalia416/NFC-Application pull request #1
Opened 2023-03-17 14:46 UTC by himalia416

2023-03-24 11:06 UTC, sylwester-zielinski requested changes

2023-03-24 11:06 UTC, sylwester-zielinski commented on app/src/main/java/com/example/nfcapplication/repository/NfcScanningManager.kt
> +            _tagTechnology.value = emptyList()
Do you need to assign this value here and later? Maybe you can do this only once with the final result?

2023-03-24 11:06 UTC, sylwester-zielinski commented on app/src/main/java/com/example/nfcapplication/repository/NfcScanningManager.kt
> +            Toast.makeText(context, "Tag disconnected. Reason: " + e.message, Toast.LENGTH_SHORT)
Why this class do any modification to UI?

2023-03-24 11:06 UTC, sylwester-zielinski commented on app/src/main/java/com/example/nfcapplication/viewmodel/NfcState.kt
> +sealed class NfcState
Looks like enum to me.

2023-03-24 11:06 UTC, sylwester-zielinski commented on app/src/main/java/com/example/nfcapplication/viewmodel/NfcViewModel.kt
> +@RequiresApi(Build.VERSION_CODES.S)
Why?

2023-03-24 11:06 UTC, sylwester-zielinski commented on app/src/main/java/com/example/nfcapplication/viewmodel/NfcViewModel.kt
> +                }.launchIn(viewModelScope)
Please improve look and feel of startNfcScanning() method.

2023-03-24 11:06 UTC, sylwester-zielinski commented on app/src/main/java/com/example/nfcapplication/viewmodel/NfcViewModel.kt
> +            state = NfcNotEnabled,
One line?

2023-03-24 11:06 UTC, sylwester-zielinski commented on app/src/main/java/com/example/nfcapplication/viewmodel/NfcViewModel.kt
> +            state = NfcNotSupported,
ditto

2023-03-24 11:06 UTC, sylwester-zielinski commented on app/src/main/java/com/example/nfcapplication/viewmodel/NfcViewModel.kt
> +            state = NfcScanTag,
ditto

2023-03-24 11:06 UTC, sylwester-zielinski commented on app/src/main/java/com/example/nfcapplication/viewmodel/NfcViewModel.kt
> +            state = EnableNfc,
ditto

2023-03-24 11:06 UTC, sylwester-zielinski commented on app/src/main/java/com/example/nfcapplication/views/ShowEnableNfcView.kt
> +        onDismissRequest = { },
Don't you need to handle this? I think it's for system back button

2023-03-24 11:06 UTC, sylwester-zielinski commented on app/src/main/res/drawable/nfc_logo512.png
Don't you have svg for better scaling and less memory usage?

2023-03-24 11:06 UTC, sylwester-zielinski commented on app/src/main/res/xml/filter_nfc.xml
> +<!--<PreferenceScreen xmlns:android="http://schemas.android.com/apk/res/android">-->
Please clean

2023-04-28 07:58 UTC, sylwester-zielinski reviewed
Generally very good.

2023-04-28 07:58 UTC, sylwester-zielinski commented on app/src/main/java/com/example/nfcapplication/component/RowInCardView.kt
> +            modifier = modifier.padding(end = 16.dp),
Maybe Spacer?

2023-04-28 07:58 UTC, sylwester-zielinski commented on app/src/main/java/com/example/nfcapplication/repository/NfcScanningManager.kt
> +        nfcAdapter = NfcAdapter.getDefaultAdapter(context)
I prefer to use (?: return). Thanks to that I don't need to do ?.let later and I have one tabulator less.

2023-04-28 07:58 UTC, sylwester-zielinski commented on app/src/main/java/com/example/nfcapplication/repository/NfcScanningManager.kt
> +    private fun getAllTagAndTransceiveLength(tag: Tag): Triple<List<String>, Int, Int> {
I would recommend using data class instead of Triple, it will increase readability.

2023-04-28 07:58 UTC, sylwester-zielinski commented on app/src/main/java/com/example/nfcapplication/repository/NfcScanningManager.kt
> +    private fun onMifareClassicTagDiscovered(
Please create 2 separate parsers for Mifare and ndef tags and put them in seperate files.

2023-04-28 07:58 UTC, sylwester-zielinski commented on app/src/main/java/com/example/nfcapplication/repository/NfcTag.kt
> +data class NdefTag(
Why MifareTag is in seperate class and NdefTag no?

2023-05-24 14:35 UTC, himalia416 commented on app/build.gradle
> +    kapt 'androidx.hilt:hilt-compiler:1.0.0'
done

2023-05-24 14:35 UTC, himalia416 commented on app/src/main/java/com/example/nfcapplication/repository/NfcScanningManager.kt
> +    val isNfcEnabled = _isNfcEnabled.asStateFlow()
done

2023-05-24 14:35 UTC, himalia416 commented on app/src/main/java/com/example/nfcapplication/repository/NfcScanningManager.kt
> +            return
fixed

2023-05-24 14:35 UTC, himalia416 commented on app/src/main/java/com/example/nfcapplication/repository/NfcScanningManager.kt
> +        initAdapter()
fixed

2023-05-24 14:35 UTC, himalia416 commented on app/src/main/java/com/example/nfcapplication/repository/NfcScanningManager.kt
> +        if (!nfcAdapter!!.isEnabled) {
fixed

2023-05-24 14:37 UTC, himalia416 commented on app/src/main/java/com/example/nfcapplication/repository/NfcScanningManager.kt
> +            _tagTechnology.value = emptyList()
fixed

2023-05-24 14:37 UTC, himalia416 commented on app/src/main/java/com/example/nfcapplication/repository/NfcScanningManager.kt
> +            Toast.makeText(context, "Tag disconnected. Reason: " + e.message, Toast.LENGTH_SHORT)
fixed

2023-05-24 14:38 UTC, himalia416 commented on app/src/main/java/com/example/nfcapplication/viewmodel/NfcViewModel.kt
> +@RequiresApi(Build.VERSION_CODES.S)
fixed

2023-05-24 14:38 UTC, himalia416 commented on app/src/main/java/com/example/nfcapplication/viewmodel/NfcViewModel.kt
> +                }.launchIn(viewModelScope)
fixed

2023-05-24 14:38 UTC, himalia416 commented on app/src/main/java/com/example/nfcapplication/viewmodel/NfcViewModel.kt
> +            state = NfcNotSupported,
fixed

2023-05-24 14:38 UTC, himalia416 commented on app/src/main/java/com/example/nfcapplication/viewmodel/NfcViewModel.kt
> +            state = EnableNfc,
fixed

2023-05-24 14:39 UTC, himalia416 commented on app/src/main/res/drawable/nfc_logo512.png
done

2023-05-24 14:39 UTC, himalia416 commented on app/src/main/res/xml/filter_nfc.xml
> +<!--<PreferenceScreen xmlns:android="http://schemas.android.com/apk/res/android">-->
done

2023-05-25 14:18 UTC, sylwester-zielinski reviewed
Fix com.example everywhere.

Commit fixes and merge.

2023-05-25 14:18 UTC, sylwester-zielinski commented on domain/src/main/java/com/example/domain/nfcTag/ndef/record/mapper/NdefRecordTypeMapper.kt
> +    private val RTD_TEXT = byteArrayOf(0x54) // "T"
Enum

2023-05-25 14:18 UTC, sylwester-zielinski commented on domain/src/main/java/com/example/domain/nfcTag/ndef/record/mapper/UriProtocolMapper.kt
> +package com.example.domain.nfcTag.ndef.record.mapper
com.example?

2023-05-25 14:18 UTC, sylwester-zielinski commented on navigation/build.gradle.kts
> +    namespace = "com.example.navigation"
com.example?

2023-05-25 14:18 UTC, sylwester-zielinski commented on profile_nfc/src/main/java/com/example/profile_nfc/repository/OnMifareTagDiscovered.kt
> +        mifareClassic?.let {
Maybe if (mifareclassic == null) return null. Then you can avoid one tab below

2023-05-25 14:18 UTC, sylwester-zielinski commented on profile_nfc/src/main/java/com/example/profile_nfc/views/tagViews/ndefTag/RecordView.kt
> +private fun DisplayUriRecord(
Maybe split this @Composables into different files

2023-05-26 13:48 UTC, himalia416 commented on settings/src/main/java/com/example/setting/views/SettingsScreenViewEvent.kt
> +sealed interface SettingsScreenViewEvent
leaving it as it because it might include some data classes

2023-05-26 14:33 UTC, sylwester-zielinski approved these changes

2023-05-26 14:33 UTC, merged