Handover connection
himalia416/NFC-Application pull request #3
Opened 2023-08-04 14:00 UTC by himalia416

2023-08-14 10:47 UTC, sylwester-zielinski requested changes

2023-08-14 10:47 UTC, sylwester-zielinski commented on app/src/main/AndroidManifest.xml
> +        android:maxSdkVersion="30"/>
Delete this line. It's not true.

2023-08-14 10:47 UTC, sylwester-zielinski commented on bleConnection/src/main/java/no/nordicsemi/bleconnection/repository/ConnectBluetoothLe.kt
> +    private val _bState: MutableStateFlow<GattConnectionState> =
Please rename to something self-explanatory like: bluetoothConnectionState

2023-08-14 10:47 UTC, sylwester-zielinski commented on bleConnection/src/main/java/no/nordicsemi/bleconnection/repository/ConnectBluetoothLe.kt
> +                val a = scanBleDevice(macAddress, scope)
What is a?

2023-08-14 10:47 UTC, sylwester-zielinski commented on bleConnection/src/main/java/no/nordicsemi/bleconnection/repository/ConnectBluetoothLe.kt
> +                continuation.resume(listOf(scanResults.device))
job.cancel() here as well.

2023-08-14 10:47 UTC, sylwester-zielinski commented on bleConnection/src/main/java/no/nordicsemi/bleconnection/view/ConnectBluetoothScreen.kt
> +        val state by viewModel.state.collectAsState()
collectAsStateWithLifecycle()

2023-08-14 10:47 UTC, sylwester-zielinski commented on bleConnection/src/main/java/no/nordicsemi/bleconnection/view/ConnectBluetoothScreen.kt
> +                    Text(text = "Bluetooth Connected with device ${state.device}")
Why do you need both Text and Toast?

2023-08-14 10:47 UTC, sylwester-zielinski commented on bleConnection/src/main/java/no/nordicsemi/bleconnection/viewmodel/ConnectBleDeviceViewModel.kt
> +            when (it) {
_state.value = _state.value.copy(bleConnectState = it)?

2023-08-14 10:47 UTC, sylwester-zielinski commented on bleConnection/src/main/java/no/nordicsemi/bleconnection/viewmodel/ConnectBleDeviceViewModel.kt
> +        connectBleDevice.disconnectBleDevice(device)
Why do you additionally disconnect device when it's state is DISCONNECTED?

2023-08-14 10:47 UTC, sylwester-zielinski commented on nfcUi/src/main/java/no/nordicsemi/ui/views/tagView/ndefmessage/ndefrecord/RecordView.kt
> +                    is OtherRecords -> TODO()
What about these TODO()?

2023-08-14 10:47 UTC, sylwester-zielinski commented on serialization/src/main/java/no/nordicsemi/serialization/repository/BluetoothDeviceSerialization.kt
> +            return BluetoothAdapter.getDefaultAdapter().getRemoteDevice(device)
Don't we need nullable value of it?

2023-08-14 13:06 UTC, sylwester-zielinski approved these changes

2023-08-14 14:37 UTC, merged

2023-08-15 11:18 UTC, philips77 commented on app/src/main/AndroidManifest.xml
> +        android:maxSdkVersion="30"/>
Not true that it uses Bluetooth Admin at all, or that max is API 30? Since 31 it was replaced by Bluetooth Scan/Connect/Advertise.